name: softi_firebase
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # softi_common:
  #     path: ../package_flutter_common
  
  softi_common:
    git:
      url: https://github.com/atoumbre/package_flutter_common.git
      ref: v0.3.1
  
  google_sign_in:
  sign_in_with_apple:

  firebase_core:
  firebase_auth:
  firebase_dynamic_links:
  cloud_firestore:
  firebase_storage:
  firebase_remote_config:

  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  # flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:

dependency_overrides:
  intl: ^0.17.0
  extended_image: 1.5.0-dev
  
flutter:

